### ISSUE TITLE
Provide full example instructions for setting it up with GitHub and Jekyll

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-archive#13]
Since we mention Jekyll and GitHub Pages as a way to host this, it's probably worth writing out the precise steps for doing so in the documentation, since that could reduce significantly the barriers to setting this up.

@robertylewis FYI in case you can provide notes on how you did this.

**Comment by showell** [comment]
We more or less have this here:

https://github.com/zulip/zulip-archive/blob/master/hosting.md

The deeper issue here isn't so much lack of documentation, but more that we just haven't played with it enough to smooth out the rough spots in setting it up.  Plus, we're also gonna want to have a story for folks like Rust that aren't necessarily doing it via Jekyll/GH.

I'm gonna close this for now since it's not super actionable, and I think we'll organically update the docs as part of general cleanup.  (I'm still hoping Robert will pass along any insight, though.)
