### ISSUE TITLE
Failure with GH Actions

### ISSUE THREAD

**Issue by robertylewis** [zulip/zulip-archive#33]
I'm finally moving the leanprover archive to your new setup, since we're refactoring the website. But I'm having some issues with the GitHub Action setup.

You can see a failing run here:

https://github.com/leanprover-community/archive2/runs/615909057?check_suite_focus=true

It's odd, because I had a successful run with an identical configuration on another repo. One difference is that GH Pages was already enabled at the start of the successful build. This shows up in the log of the successful build:
```
Successfully installed pyyaml-5.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
{
100   156  100   143  100    13   1833    166 --:--:-- --:--:-- --:--:--  2000
  "message": "GitHub Pages is already enabled.",
  "documentation_url": "https://developer.github.com/v3/repos/pages/#enable-a-pages-site"
}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   251  100   251    0     0   3217      0 --:--:-- --:--:-- --:--:--  3217
```
where the failing one errors.

I'm not familiar enough with Actions infrastructure to diagnose what's going wrong. If it's expected that Pages is enabled at the start, maybe this could go in the instructions?

**Comment by timabbott** [comment]
Hmm, that's not obviously an error.  Did you try just retrying?  I could imagine there being some sort of operational error on the GitHub side.

**Comment by timabbott** [comment]
This seems to be the actual traceback in that build, though:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'html_url'
```

**Comment by robertylewis** [comment]
I did retry it; it definitely seems to be an error caused by GH Pages not being enabled. The action succeeded in a repo with Pages enabled, failed consistently in two others, and succeeded when I enabled Pages in one of the failing ones.

I guess it's connected to [this line](https://github.com/zulip/zulip-archive/blob/master/entrypoint.sh#L39) but I'm not certain. (I don't know what the state is when the entry point script is called.)

**Comment by refeed** [comment]
FYI, I did some investigation in this

Failed one:
https://github.com/refeed/zarchive-refeed/runs/7281144172?check_suite_focus=true
I realized that I got this when my GitHub PAT was wrong (I put the secret in "Environment secrets" instead of "Repository secrets", I should've put it in "Repository secrets" instead) .I guess anyone can get this also when one didn't give enough permission to the PAT key. GitHub's side operational error could also be the cause, but not for my case though

Successful one:
https://github.com/refeed/zarchive-refeed/runs/7281327132?check_suite_focus=true
I fixed my GitHub PAT key, and the script worked although GitHub pages wasn't enabled previously.

I also think the failed one was throwing exception on this line: https://github.com/zulip/zulip-archive/blob/5da606feac0fa69445de717c406f79dd81e82e59/entrypoint.sh#L47 .
