### ISSUE TITLE
Strengthen URL escaping

### ISSUE THREAD

**Issue by robertylewis** [zulip/zulip-archive#35]
The current escaping for URLs isn't strong enough. #34 fixed escaping `?` which was causing broken links. But there are other bad symbols coming through. 

Here's a URL which works but is malformed: https://leanprover-community.github.io/archive/stream/218272-FoMM-/-Lean-Together-2020/index.html (notice it's in a subdirectory of `/stream/21872-FoMM-`). The Zulip URL for this stream is better, https://leanprover.zulipchat.com/#narrow/stream/218272-FoMM-.2F.20Lean.20Together.202020

I haven't noticed other malformed links yet but I expect to find some. Our users like to make annoying stream/topic names. The Zulip escaping seems to be 100% reliable for us, even with the annoying names, so maybe that should be duplicated here?

One note, URL changes are disruptive, so this probably shouldn't be done incrementally. If anything is changing it should all change at once.

**Comment by robertylewis** [comment]
The `#` symbol also causes problems. See the link to topic `#mwe bot` [here](https://leanprover-community.github.io/archive/stream/236604-Zulip-meta/index.html),
which directs to [a broken link](https://leanprover-community.github.io/archive/stream/236604-Zulip-meta/topic/.23mwe.20bot.html).

**Comment by vvs-** [comment]
Also, see https://github.com/leanprover-community/archive/issues/2.

**Comment by fpvandoorn** [comment]
Topics starting with `"` lead to broken links.

**Comment by refeed** [comment]
About broken links when special characters like `#` and `"` is the first char in the topic name, it is actually caused by jekyll in gh-pages ignoring files that starts with `.` (because for example `#` is sanitized to `.23`). One solution is to create a `.nojekyll` in the repo so that the jekyll in gh-pages is disabled.

https://github.community/t/does-github-pages-support-folders-starting-with-a-dot/146900

There's a commit that added script to add `.nojekyll` at https://github.com/zulip/zulip-archive/commit/18507eb3c0e108af2a1d150c7f6316ba70907bb9
