### ISSUE TITLE
Support GH Pages theme chooser

### ISSUE THREAD

**Issue by BWPanda** [zulip/zulip-archive#52]
This is my first time using GH Pages, so I was interested to see the theme chooser in my repo's settings. Especially after discovering that the archive pages were very bland indeed...

Unfortunately it doesn't seem to make any difference choosing a theme from the settings. I cannot make my archive look nice. Does support for the theme chooser need to be added to this project, or am I just missing something?

**Comment by timabbott** [comment]
Certainly there's work one could do to contribute a nicer stylesheet for zulip-archive, but it's unlikely to be a big priority since I expect most use of zulip-archive to be replaced by the upcoming native in-Zulip archive system.

Closing since I'm not sure how the GitHub Pages theme chooser works but it seems likely we'd address the styling by integrating with that (vs. e.g. copying stylesheet code from the Zulip webapp).
